#!/bin/bash

if [ $1 == cleanup ]
then
    make clean
    rm -rf depcomp install-sh missing Makefile Makefile.in stamp-h1 config.status configure config.log config.h* autom4te.cache/ aclocal.m4 src/.deps src/Makefile src/Makefile.in INSTALL
else
    #libtoolize
    aclocal
    autoconf
    autoheader
    automake --add-missing --foreign
    autoreconf

    ./configure
fi
